language: php

php:
    - 5.6
    - 7.1
    - 7.2

env:
    - WP_VERSION=latest WP_MULTISITE=0

before_script:
    - bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit
