# Travis CI Configuration File

# Use Travis CI's faster Docker-based infrastructure.
sudo: false

# Tell Travis CI we're using PHP
language: php

php:
	- 5.2
	- 5.3
	- 5.4
	- 5.5
	- 5.6
	- hhvm

env:
	- WP_VERSION=latest WP_MULTISITE=0
	- WP_VERSION=latest WP_MULTISITE=1
	- WP_VERSION=3.8 WP_MULTISITE=0
	- WP_VERSION=3.8 WP_MULTISITE=1

